export const COUNTRIES = [
  {
    from: "afegãne",
    country_name: "Afeganistão",
    country_name_int: "Afghanistan",
    abbreviation: "AF",
  },
  {
    from: "sul-africana",
    country_name: "África do Sul",
    country_name_int: "South Africa",
    abbreviation: "ZA",
  },
  {
    from: "albanesa",
    country_name: "Albânia",
    country_name_int: "Albania",
    abbreviation: "AL",
  },
  {
    from: "alemã",
    country_name: "Alemanha",
    country_name_int: "Germany",
    abbreviation: "DE",
  },
  {
    from: "andorrana",
    country_name: "Andorra",
    country_name_int: "Andorra",
    abbreviation: "AD",
  },
  {
    from: "angolana",
    country_name: "Angola",
    country_name_int: "Angola",
    abbreviation: "AO",
  },
  {
    from: "anguillana",
    country_name: "Anguilla",
    country_name_int: "Anguilla",
    abbreviation: "AI",
  },
  {
    from: "de antártida",
    country_name: "Antártida",
    country_name_int: "Antarctica",
    abbreviation: "AQ",
  },
  {
    from: "antiguana",
    country_name: "Antígua e Barbuda",
    country_name_int: "Antigua & Barbuda",
    abbreviation: "AG",
  },
  {
    from: "saudita",
    country_name: "Arábia Saudita",
    country_name_int: "Saudi Arabia",
    abbreviation: "SA",
  },
  {
    from: "argelina",
    country_name: "Argélia",
    country_name_int: "Algeria",
    abbreviation: "DZ",
  },
  {
    from: "argentina",
    country_name: "Argentina",
    country_name_int: "Argentina",
    abbreviation: "AR",
  },
  {
    from: "armênia",
    country_name: "Armênia",
    country_name_int: "Armenia",
    abbreviation: "AM",
  },
  {
    from: "arubana",
    country_name: "Aruba",
    country_name_int: "Aruba",
    abbreviation: "AW",
  },
  {
    from: "australiana",
    country_name: "Austrália",
    country_name_int: "Australia",
    abbreviation: "AU",
  },
  {
    from: "austríaca",
    country_name: "Áustria",
    country_name_int: "Austria",
    abbreviation: "AT",
  },
  {
    from: "azerbaijano",
    country_name: "Azerbaijão",
    country_name_int: "Azerbaijan",
    abbreviation: "AZ",
  },
  {
    from: "bahamense",
    country_name: "Bahamas",
    country_name_int: "Bahamas",
    abbreviation: "BS",
  },
  {
    from: "barenita",
    country_name: "Bahrein",
    country_name_int: "Bahrain",
    abbreviation: "BH",
  },
  {
    from: "bengali",
    country_name: "Bangladesh",
    country_name_int: "Bangladesh",
    abbreviation: "BD",
  },
  {
    from: "barbadiana",
    country_name: "Barbados",
    country_name_int: "Barbados",
    abbreviation: "BB",
  },
  {
    from: "bielo-russa",
    country_name: "Belarus",
    country_name_int: "Belarus",
    abbreviation: "BY",
  },
  {
    from: "belga",
    country_name: "Bélgica",
    country_name_int: "Belgium",
    abbreviation: "BE",
  },
  {
    from: "belizenha",
    country_name: "Belize",
    country_name_int: "Belize",
    abbreviation: "BZ",
  },
  {
    from: "beninense",
    country_name: "Benin",
    country_name_int: "Benin",
    abbreviation: "BJ",
  },
  {
    from: "bermudiana",
    country_name: "Bermudas",
    country_name_int: "Bermuda",
    abbreviation: "BM",
  },
  {
    from: "boliviana",
    country_name: "Bolívia",
    country_name_int: "Bolivia",
    abbreviation: "BO",
  },
  {
    from: "bósnia",
    country_name: "Bósnia-Herzegóvina",
    country_name_int: "Bosnia & Herzegovina",
    abbreviation: "BA",
  },
  {
    from: "betchuana",
    country_name: "Botsuana",
    country_name_int: "Botswana",
    abbreviation: "BW",
  },
  {
    from: "brasileira",
    country_name: "Brasil",
    country_name_int: "Brazil",
    abbreviation: "BR",
  },
  {
    from: "bruneiana",
    country_name: "Brunei",
    country_name_int: "Brunei",
    abbreviation: "BN",
  },
  {
    from: "búlgara",
    country_name: "Bulgária",
    country_name_int: "Bulgaria",
    abbreviation: "BG",
  },
  {
    from: "burquinês",
    country_name: "Burkina Fasso",
    country_name_int: "Burkina Faso",
    abbreviation: "BF",
  },
  {
    from: "burundinesa",
    country_name: "Burundi",
    country_name_int: "Burundi",
    abbreviation: "BI",
  },
  {
    from: "butanesa",
    country_name: "Butão",
    country_name_int: "Bhutan",
    abbreviation: "BT",
  },
  {
    from: "cabo-verdiana",
    country_name: "Cabo Verde",
    country_name_int: "Cape Verde",
    abbreviation: "CV",
  },
  {
    from: "camaronesa",
    country_name: "Camarões",
    country_name_int: "Cameroon",
    abbreviation: "CM",
  },
  {
    from: "cambojana",
    country_name: "Camboja",
    country_name_int: "Cambodia",
    abbreviation: "KH",
  },
  {
    from: "canadense",
    country_name: "Canadá",
    country_name_int: "Canada",
    abbreviation: "CA",
  },
  {
    from: "canário",
    country_name: "Canárias",
    country_name_int: "Canary Islands",
    abbreviation: "IC",
  },
  {
    from: "cazaque",
    country_name: "Cazaquistão",
    country_name_int: "Kazakhstan",
    abbreviation: "KZ",
  },
  {
    from: "de ceuta e melilla",
    country_name: "Ceuta e Melilla",
    country_name_int: "Ceuta & Melilla",
    abbreviation: "EA",
  },
  {
    from: "chadiana",
    country_name: "Chade",
    country_name_int: "Chad",
    abbreviation: "TD",
  },
  {
    from: "chilena",
    country_name: "Chile",
    country_name_int: "Chile",
    abbreviation: "CL",
  },
  {
    from: "chinesa",
    country_name: "China",
    country_name_int: "China",
    abbreviation: "CN",
  },
  {
    from: "cipriota",
    country_name: "Chipre",
    country_name_int: "Cyprus",
    abbreviation: "CY",
  },
  {
    from: "cingapuriana",
    country_name: "Cingapura",
    country_name_int: "Singapore",
    abbreviation: "SG",
  },
  {
    from: "colombiana",
    country_name: "Colômbia",
    country_name_int: "Colombia",
    abbreviation: "CO",
  },
  {
    from: "comorense",
    country_name: "Comores",
    country_name_int: "Comoros",
    abbreviation: "KM",
  },
  {
    from: "congolesa",
    country_name: "Congo",
    country_name_int: "Congo (Republic)",
    abbreviation: "CG",
  },
  {
    from: "norte-coreano",
    country_name: "Coréia do Norte",
    country_name_int: "North Korea",
    abbreviation: "KP",
  },
  {
    from: "norte-coreana",
    country_name: "Coréia do Sul",
    country_name_int: "South Korea",
    abbreviation: "KR",
  },
  {
    from: "marfinense",
    country_name: "Costa do Marfim",
    country_name_int: "Côte d¿Ivoire",
    abbreviation: "CI",
  },
  {
    from: "costarriquenha",
    country_name: "Costa Rica",
    country_name_int: "Costa Rica",
    abbreviation: "CR",
  },
  {
    from: "croata",
    country_name: "Croácia",
    country_name_int: "Croatia",
    abbreviation: "HR",
  },
  {
    from: "cubana",
    country_name: "Cuba",
    country_name_int: "Cuba",
    abbreviation: "CU",
  },
  {
    from: "curaçauense",
    country_name: "Curaçao",
    country_name_int: "Curaçao",
    abbreviation: "CW",
  },
  {
    from: "chagositano",
    country_name: "Diego Garcia",
    country_name_int: "Diego Garcia",
    abbreviation: "DG",
  },
  {
    from: "dinamarquesa",
    country_name: "Dinamarca",
    country_name_int: "Denmark",
    abbreviation: "DK",
  },
  {
    from: "djibutiana",
    country_name: "Djibuti",
    country_name_int: "Djibouti",
    abbreviation: "DJ",
  },
  {
    from: "dominiquense",
    country_name: "Dominica",
    country_name_int: "Dominica",
    abbreviation: "DM",
  },
  {
    from: "egípcia",
    country_name: "Egito",
    country_name_int: "Egypt",
    abbreviation: "EG",
  },
  {
    from: "salvadorenha",
    country_name: "El Salvador",
    country_name_int: "El Salvador",
    abbreviation: "SV",
  },
  {
    from: "árabe",
    country_name: "Emirados Árabes Unidos",
    country_name_int: "United Arab Emirates",
    abbreviation: "AE",
  },
  {
    from: "equatoriana",
    country_name: "Equador",
    country_name_int: "Ecuador",
    abbreviation: "EC",
  },
  {
    from: "eritreia",
    country_name: "Eritréia",
    country_name_int: "Eritrea",
    abbreviation: "ER",
  },
  {
    from: "eslovaco",
    country_name: "Eslováquia",
    country_name_int: "Slovakia",
    abbreviation: "SK",
  },
  {
    from: "esloveno",
    country_name: "Eslovênia",
    country_name_int: "Slovenia",
    abbreviation: "SI",
  },
  {
    from: "espanhola",
    country_name: "Espanha",
    country_name_int: "Spain",
    abbreviation: "ES",
  },
  {
    from: "norte-americana",
    country_name: "Estados Unidos",
    country_name_int: "United States",
    abbreviation: "US",
  },
  {
    from: "estoniana",
    country_name: "Estônia",
    country_name_int: "Estonia",
    abbreviation: "EE",
  },
  {
    from: "etíope",
    country_name: "Etiópia",
    country_name_int: "Ethiopia",
    abbreviation: "ET",
  },
  {
    from: "fijiana",
    country_name: "Fiji",
    country_name_int: "Fiji",
    abbreviation: "FJ",
  },
  {
    from: "filipina",
    country_name: "Filipinas",
    country_name_int: "Philippines",
    abbreviation: "PH",
  },
  {
    from: "finlandesa",
    country_name: "Finlândia",
    country_name_int: "Finland",
    abbreviation: "FI",
  },
  {
    from: "francesa",
    country_name: "França",
    country_name_int: "France",
    abbreviation: "FR",
  },
  {
    from: "gabonesa",
    country_name: "Gabão",
    country_name_int: "Gabon",
    abbreviation: "GA",
  },
  {
    from: "gambiana",
    country_name: "Gâmbia",
    country_name_int: "Gambia",
    abbreviation: "GM",
  },
  {
    from: "ganense",
    country_name: "Gana",
    country_name_int: "Ghana",
    abbreviation: "GH",
  },
  {
    from: "georgiana",
    country_name: "Geórgia",
    country_name_int: "Georgia",
    abbreviation: "GE",
  },
  {
    from: "gibraltariana",
    country_name: "Gibraltar",
    country_name_int: "Gibraltar",
    abbreviation: "GI",
  },
  {
    from: "inglesa",
    country_name: "Grã-Bretanha (Reino Unido, UK)",
    country_name_int: "United Kingdom",
    abbreviation: "GB",
  },
  {
    from: "granadina",
    country_name: "Granada",
    country_name_int: "Grenada",
    abbreviation: "GD",
  },
  {
    from: "grega",
    country_name: "Grécia",
    country_name_int: "Greece",
    abbreviation: "GR",
  },
  {
    from: "groenlandesa",
    country_name: "Groelândia",
    country_name_int: "Greenland",
    abbreviation: "GL",
  },
  {
    from: "guadalupense",
    country_name: "Guadalupe",
    country_name_int: "Guadeloupe",
    abbreviation: "GP",
  },
  {
    from: "guamês",
    country_name: "Guam (Território dos Estados Unidos)",
    country_name_int: "Guam",
    abbreviation: "GU",
  },
  {
    from: "guatemalteca",
    country_name: "Guatemala",
    country_name_int: "Guatemala",
    abbreviation: "GT",
  },
  {
    from: "guernesiano",
    country_name: "Guernsey",
    country_name_int: "Guernsey",
    abbreviation: "GG",
  },
  {
    from: "guianense",
    country_name: "Guiana",
    country_name_int: "Guyana",
    abbreviation: "GY",
  },
  {
    from: "franco-guianense",
    country_name: "Guiana Francesa",
    country_name_int: "French Guiana",
    abbreviation: "GF",
  },
  {
    from: "guinéu-equatoriano ou equatoguineana",
    country_name: "Guiné",
    country_name_int: "Guinea",
    abbreviation: "GN",
  },
  {
    from: "guinéu-equatoriano",
    country_name: "Guiné Equatorial",
    country_name_int: "Equatorial Guinea",
    abbreviation: "GQ",
  },
  {
    from: "guineense",
    country_name: "Guiné-Bissau",
    country_name_int: "Guinea-Bissau",
    abbreviation: "GW",
  },
  {
    from: "haitiana",
    country_name: "Haiti",
    country_name_int: "Haiti",
    abbreviation: "HT",
  },
  {
    from: "holandês",
    country_name: "Holanda",
    country_name_int: "Netherlands",
    abbreviation: "NL",
  },
  {
    from: "hondurenha",
    country_name: "Honduras",
    country_name_int: "Honduras",
    abbreviation: "HN",
  },
  {
    from: "hong-konguiana ou chinesa",
    country_name: "Hong Kong",
    country_name_int: "Hong Kong",
    abbreviation: "HK",
  },
  {
    from: "húngara",
    country_name: "Hungria",
    country_name_int: "Hungary",
    abbreviation: "HU",
  },
  {
    from: "iemenita",
    country_name: "Iêmen",
    country_name_int: "Yemen",
    abbreviation: "YE",
  },
  {
    from: "da ilha bouvet",
    country_name: "Ilha Bouvet",
    country_name_int: "Bouvet Island",
    abbreviation: "BV",
  },
  {
    from: "da ilha de ascensão",
    country_name: "Ilha de Ascensão",
    country_name_int: "Ascension Island",
    abbreviation: "AC",
  },
  {
    from: "da ilha de clipperton",
    country_name: "Ilha de Clipperton",
    country_name_int: "Clipperton Island",
    abbreviation: "CP",
  },
  {
    from: "manês",
    country_name: "Ilha de Man",
    country_name_int: "Isle of Man",
    abbreviation: "IM",
  },
  {
    from: "natalense",
    country_name: "Ilha Natal",
    country_name_int: "Christmas Island",
    abbreviation: "CX",
  },
  {
    from: "pitcairnense",
    country_name: "Ilha Pitcairn",
    country_name_int: "Pitcairn Islands",
    abbreviation: "PN",
  },
  {
    from: "reunionense",
    country_name: "Ilha Reunião",
    country_name_int: "Réunion",
    abbreviation: "RE",
  },
  {
    from: "alandês",
    country_name: "Ilhas Aland",
    country_name_int: "Åland Islands",
    abbreviation: "AX",
  },
  {
    from: "caimanês",
    country_name: "Ilhas Cayman",
    country_name_int: "Cayman Islands",
    abbreviation: "KY",
  },
  {
    from: "coquense",
    country_name: "Ilhas Cocos",
    country_name_int: "Cocos (Keeling) Islands",
    abbreviation: "CC",
  },
  {
    from: "cookense",
    country_name: "Ilhas Cook",
    country_name_int: "Cook Islands",
    abbreviation: "CK",
  },
  {
    from: "faroense",
    country_name: "Ilhas Faroes",
    country_name_int: "Faroe Islands",
    abbreviation: "FO",
  },
  {
    from: "das ilhas geórgia do sul e sandwich do sul",
    country_name: "Ilhas Geórgia do Sul e Sandwich do Sul",
    country_name_int: "South Georgia & South Sandwich Islands",
    abbreviation: "GS",
  },
  {
    from: "das ilhas heard e mcdonald",
    country_name: "Ilhas Heard e McDonald (Território da Austrália)",
    country_name_int: "Heard & McDonald Islands",
    abbreviation: "HM",
  },
  {
    from: "malvinense",
    country_name: "Ilhas Malvinas",
    country_name_int: "Falkland Islands (Islas Malvinas)",
    abbreviation: "FK",
  },
  {
    from: "norte-marianense",
    country_name: "Ilhas Marianas do Norte",
    country_name_int: "Northern Mariana Islands",
    abbreviation: "MP",
  },
  {
    from: "marshallino",
    country_name: "Ilhas Marshall",
    country_name_int: "Marshall Islands",
    abbreviation: "MH",
  },
  {
    from: "das ilhas menores afastadas",
    country_name: "Ilhas Menores dos Estados Unidos",
    country_name_int: "U.S. Outlying Islands",
    abbreviation: "UM",
  },
  {
    from: "norfolquino",
    country_name: "Ilhas Norfolk",
    country_name_int: "Norfolk Island",
    abbreviation: "NF",
  },
  {
    from: "salomônico",
    country_name: "Ilhas Salomão",
    country_name_int: "Solomon Islands",
    abbreviation: "SB",
  },
  {
    from: "seichelense",
    country_name: "Ilhas Seychelles",
    country_name_int: "Seychelles",
    abbreviation: "SC",
  },
  {
    from: "toquelauano",
    country_name: "Ilhas Tokelau",
    country_name_int: "Tokelau",
    abbreviation: "TK",
  },
  {
    from: "turquês",
    country_name: "Ilhas Turks e Caicos",
    country_name_int: "Turks & Caicos Islands",
    abbreviation: "TC",
  },
  {
    from: "virginense",
    country_name: "Ilhas Virgens (Estados Unidos)",
    country_name_int: "U.S. Virgin Islands",
    abbreviation: "VI",
  },
  {
    from: "virginense",
    country_name: "Ilhas Virgens (Inglaterra)",
    country_name_int: "British Virgin Islands",
    abbreviation: "VG",
  },
  {
    from: "indiano",
    country_name: "Índia",
    country_name_int: "India",
    abbreviation: "IN",
  },
  {
    from: "indonésia",
    country_name: "Indonésia",
    country_name_int: "Indonesia",
    abbreviation: "ID",
  },
  {
    from: "iraniano",
    country_name: "Irã",
    country_name_int: "Iran",
    abbreviation: "IR",
  },
  {
    from: "iraquiana",
    country_name: "Iraque",
    country_name_int: "Iraq",
    abbreviation: "IQ",
  },
  {
    from: "irlandesa",
    country_name: "Irlanda",
    country_name_int: "Ireland",
    abbreviation: "IE",
  },
  {
    from: "islandesa",
    country_name: "Islândia",
    country_name_int: "Iceland",
    abbreviation: "IS",
  },
  {
    from: "israelense",
    country_name: "Israel",
    country_name_int: "Israel",
    abbreviation: "IL",
  },
  {
    from: "italiana",
    country_name: "Itália",
    country_name_int: "Italy",
    abbreviation: "IT",
  },
  {
    from: "jamaicana",
    country_name: "Jamaica",
    country_name_int: "Jamaica",
    abbreviation: "JM",
  },
  {
    from: "japonesa",
    country_name: "Japão",
    country_name_int: "Japan",
    abbreviation: "JP",
  },
  {
    from: "canalina",
    country_name: "Jersey",
    country_name_int: "Jersey",
    abbreviation: "JE",
  },
  {
    from: "jordaniana",
    country_name: "Jordânia",
    country_name_int: "Jordan",
    abbreviation: "JO",
  },
  {
    from: "kiribatiana",
    country_name: "Kiribati",
    country_name_int: "Kiribati",
    abbreviation: "KI",
  },
  {
    from: "kosovar",
    country_name: "Kosovo",
    country_name_int: "Kosovo",
    abbreviation: "XK",
  },
  {
    from: "kuwaitiano",
    country_name: "Kuait",
    country_name_int: "Kuwait",
    abbreviation: "KW",
  },
  {
    from: "laosiana",
    country_name: "Laos",
    country_name_int: "Laos",
    abbreviation: "LA",
  },
  {
    from: "lesota",
    country_name: "Lesoto",
    country_name_int: "Lesotho",
    abbreviation: "LS",
  },
  {
    from: "letão",
    country_name: "Letônia",
    country_name_int: "Latvia",
    abbreviation: "LV",
  },
  {
    from: "libanesa",
    country_name: "Líbano",
    country_name_int: "Lebanon",
    abbreviation: "LB",
  },
  {
    from: "liberiana",
    country_name: "Libéria",
    country_name_int: "Liberia",
    abbreviation: "LR",
  },
  {
    from: "líbia",
    country_name: "Líbia",
    country_name_int: "Libya",
    abbreviation: "LY",
  },
  {
    from: "liechtensteiniense",
    country_name: "Liechtenstein",
    country_name_int: "Liechtenstein",
    abbreviation: "LI",
  },
  {
    from: "lituana",
    country_name: "Lituânia",
    country_name_int: "Lithuania",
    abbreviation: "LT",
  },
  {
    from: "luxemburguesa",
    country_name: "Luxemburgo",
    country_name_int: "Luxembourg",
    abbreviation: "LU",
  },
  {
    from: "macauense",
    country_name: "Macau",
    country_name_int: "Macau",
    abbreviation: "MO",
  },
  {
    from: "macedônio",
    country_name: "Macedônia (República Yugoslava)",
    country_name_int: "Macedonia (FYROM)",
    abbreviation: "MK",
  },
  {
    from: "malgaxe",
    country_name: "Madagascar",
    country_name_int: "Madagascar",
    abbreviation: "MG",
  },
  {
    from: "malaia",
    country_name: "Malásia",
    country_name_int: "Malaysia",
    abbreviation: "MY",
  },
  {
    from: "malauiano",
    country_name: "Malaui",
    country_name_int: "Malawi",
    abbreviation: "MW",
  },
  {
    from: "maldívia",
    country_name: "Maldivas",
    country_name_int: "Maldives",
    abbreviation: "MV",
  },
  {
    from: "malinesa",
    country_name: "Mali",
    country_name_int: "Mali",
    abbreviation: "ML",
  },
  {
    from: "maltesa",
    country_name: "Malta",
    country_name_int: "Malta",
    abbreviation: "MT",
  },
  {
    from: "marroquina",
    country_name: "Marrocos",
    country_name_int: "Morocco",
    abbreviation: "MA",
  },
  {
    from: "martiniquense",
    country_name: "Martinica",
    country_name_int: "Martinique",
    abbreviation: "MQ",
  },
  {
    from: "mauriciana",
    country_name: "Maurício",
    country_name_int: "Mauritius",
    abbreviation: "MU",
  },
  {
    from: "mauritana",
    country_name: "Mauritânia",
    country_name_int: "Mauritania",
    abbreviation: "MR",
  },
  {
    from: "maiotense",
    country_name: "Mayotte",
    country_name_int: "Mayotte",
    abbreviation: "YT",
  },
  {
    from: "mexicana",
    country_name: "México",
    country_name_int: "Mexico",
    abbreviation: "MX",
  },
  {
    from: "micronésia",
    country_name: "Micronésia",
    country_name_int: "Micronesia",
    abbreviation: "FM",
  },
  {
    from: "moçambicana",
    country_name: "Moçambique",
    country_name_int: "Mozambique",
    abbreviation: "MZ",
  },
  {
    from: "moldavo",
    country_name: "Moldova",
    country_name_int: "Moldova",
    abbreviation: "MD",
  },
  {
    from: "monegasca",
    country_name: "Mônaco",
    country_name_int: "Monaco",
    abbreviation: "MC",
  },
  {
    from: "mongol",
    country_name: "Mongólia",
    country_name_int: "Mongolia",
    abbreviation: "MN",
  },
  {
    from: "montenegra",
    country_name: "Montenegro",
    country_name_int: "Montenegro",
    abbreviation: "ME",
  },
  {
    from: "montserratiano",
    country_name: "Montserrat",
    country_name_int: "Montserrat",
    abbreviation: "MS",
  },
  {
    from: "birmanês",
    country_name: "Myanma",
    country_name_int: "Myanmar (Burma)",
    abbreviation: "MM",
  },
  {
    from: "namíbia",
    country_name: "Namíbia",
    country_name_int: "Namibia",
    abbreviation: "NA",
  },
  {
    from: "nauruana",
    country_name: "Nauru",
    country_name_int: "Nauru",
    abbreviation: "NR",
  },
  {
    from: "nepalesa",
    country_name: "Nepal",
    country_name_int: "Nepal",
    abbreviation: "NP",
  },
  {
    from: "nicaraguense",
    country_name: "Nicarágua",
    country_name_int: "Nicaragua",
    abbreviation: "NI",
  },
  {
    from: "nigerina",
    country_name: "Níger",
    country_name_int: "Niger",
    abbreviation: "NE",
  },
  {
    from: "nigeriana",
    country_name: "Nigéria",
    country_name_int: "Nigeria",
    abbreviation: "NG",
  },
  {
    from: "niueana",
    country_name: "Niue",
    country_name_int: "Niue",
    abbreviation: "NU",
  },
  {
    from: "norueguesa",
    country_name: "Noruega",
    country_name_int: "Norway",
    abbreviation: "NO",
  },
  {
    from: "caledônia",
    country_name: "Nova Caledônia",
    country_name_int: "New Caledonia",
    abbreviation: "NC",
  },
  {
    from: "neozelandesa",
    country_name: "Nova Zelândia",
    country_name_int: "New Zealand",
    abbreviation: "NZ",
  },
  {
    from: "omani",
    country_name: "Omã",
    country_name_int: "Oman",
    abbreviation: "OM",
  },
  {
    from: "dos países baixos caribenhos",
    country_name: "Países Baixos Caribenhos",
    country_name_int: "Caribbean Netherlands",
    abbreviation: "BQ",
  },
  {
    from: "palauense",
    country_name: "Palau",
    country_name_int: "Palau",
    abbreviation: "PW",
  },
  {
    from: "palestino",
    country_name: "Palestina",
    country_name_int: "Palestine",
    abbreviation: "PS",
  },
  {
    from: "zona do canal do panamá",
    country_name: "Panamá",
    country_name_int: "Panama",
    abbreviation: "PA",
  },
  {
    from: "pauásia",
    country_name: "Papua-Nova Guiné",
    country_name_int: "Papua New Guinea",
    abbreviation: "PG",
  },
  {
    from: "paquistanesa",
    country_name: "Paquistão",
    country_name_int: "Pakistan",
    abbreviation: "PK",
  },
  {
    from: "paraguaia",
    country_name: "Paraguai",
    country_name_int: "Paraguay",
    abbreviation: "PY",
  },
  {
    from: "peruana",
    country_name: "Peru",
    country_name_int: "Peru",
    abbreviation: "PE",
  },
  {
    from: "franco-polinésia",
    country_name: "Polinésia Francesa",
    country_name_int: "French Polynesia",
    abbreviation: "PF",
  },
  {
    from: "polonesa",
    country_name: "Polônia",
    country_name_int: "Poland",
    abbreviation: "PL",
  },
  {
    from: "portorriquenha",
    country_name: "Porto Rico",
    country_name_int: "Puerto Rico",
    abbreviation: "PR",
  },
  {
    from: "portuguesa",
    country_name: "Portugal",
    country_name_int: "Portugal",
    abbreviation: "PT",
  },
  {
    from: "catarense",
    country_name: "Qatar",
    country_name_int: "Qatar",
    abbreviation: "QA",
  },
  {
    from: "queniano",
    country_name: "Quênia",
    country_name_int: "Kenya",
    abbreviation: "KE",
  },
  {
    from: "quirguiz",
    country_name: "Quirguistão",
    country_name_int: "Kyrgyzstan",
    abbreviation: "KG",
  },
  {
    from: "centro-africana",
    country_name: "República Centro-Africana",
    country_name_int: "Central African Republic",
    abbreviation: "CF",
  },
  {
    from: "congolesa",
    country_name: "República Democrática do Congo",
    country_name_int: "Congo (DRC)",
    abbreviation: "CD",
  },
  {
    from: "dominicana",
    country_name: "República Dominicana",
    country_name_int: "Dominican Republic",
    abbreviation: "DO",
  },
  {
    from: "tcheco",
    country_name: "República Tcheca",
    country_name_int: "Czech Republic",
    abbreviation: "CZ",
  },
  {
    from: "romena",
    country_name: "Romênia",
    country_name_int: "Romania",
    abbreviation: "RO",
  },
  {
    from: "ruandesa",
    country_name: "Ruanda",
    country_name_int: "Rwanda",
    abbreviation: "RW",
  },
  {
    from: "russa",
    country_name: "Rússia (antiga URSS) - Federação Russa",
    country_name_int: "Russia",
    abbreviation: "RU",
  },
  {
    from: "saariano",
    country_name: "Saara Ocidental",
    country_name_int: "Western Sahara",
    abbreviation: "EH",
  },
  {
    from: "pedro-miquelonense",
    country_name: "Saint-Pierre e Miquelon",
    country_name_int: "St. Pierre & Miquelon",
    abbreviation: "PM",
  },
  {
    from: "samoana",
    country_name: "Samoa Americana",
    country_name_int: "American Samoa",
    abbreviation: "AS",
  },
  {
    from: "samoano",
    country_name: "Samoa Ocidental",
    country_name_int: "Samoa",
    abbreviation: "WS",
  },
  {
    from: "samarinês",
    country_name: "San Marino",
    country_name_int: "San Marino",
    abbreviation: "SM",
  },
  {
    from: "helenense",
    country_name: "Santa Helena",
    country_name_int: "St. Helena",
    abbreviation: "SH",
  },
  {
    from: "santa-lucense",
    country_name: "Santa Lúcia",
    country_name_int: "St. Lucia",
    abbreviation: "LC",
  },
  {
    from: "são-bartolomeense",
    country_name: "São Bartolomeu",
    country_name_int: "St. Barthélemy",
    abbreviation: "BL",
  },
  {
    from: "são-cristovense",
    country_name: "São Cristóvão e Névis",
    country_name_int: "St. Kitts & Nevis",
    abbreviation: "KN",
  },
  {
    from: "são-martinhense",
    country_name: "São Martim",
    country_name_int: "St. Martin",
    abbreviation: "MF",
  },
  {
    from: "são-martinhense",
    country_name: "São Martinho",
    country_name_int: "Sint Maarten",
    abbreviation: "SX",
  },
  {
    from: "são-tomense",
    country_name: "São Tomé e Príncipe",
    country_name_int: "São Tomé & Príncipe",
    abbreviation: "ST",
  },
  {
    from: "sao-vicentino",
    country_name: "São Vicente e Granadinas",
    country_name_int: "St. Vincent & Grenadines",
    abbreviation: "VC",
  },
  {
    from: "senegalesa",
    country_name: "Senegal",
    country_name_int: "Senegal",
    abbreviation: "SN",
  },
  {
    from: "leonesa",
    country_name: "Serra Leoa",
    country_name_int: "Sierra Leone",
    abbreviation: "SL",
  },
  {
    from: "sérvia",
    country_name: "Sérvia",
    country_name_int: "Serbia",
    abbreviation: "RS",
  },
  {
    from: "síria",
    country_name: "Síria",
    country_name_int: "Syria",
    abbreviation: "SY",
  },
  {
    from: "somali",
    country_name: "Somália",
    country_name_int: "Somalia",
    abbreviation: "SO",
  },
  {
    from: "cingalesa",
    country_name: "Sri Lanka",
    country_name_int: "Sri Lanka",
    abbreviation: "LK",
  },
  {
    from: "suazi",
    country_name: "Suazilândia",
    country_name_int: "Swaziland",
    abbreviation: "SZ",
  },
  {
    from: "sudanesa",
    country_name: "Sudão",
    country_name_int: "Sudan",
    abbreviation: "SD",
  },
  {
    from: "sul-sudanês",
    country_name: "Sudão do Sul",
    country_name_int: "South Sudan",
    abbreviation: "SS",
  },
  {
    from: "sueca",
    country_name: "Suécia",
    country_name_int: "Sweden",
    abbreviation: "SE",
  },
  {
    from: "suíça",
    country_name: "Suíça",
    country_name_int: "Switzerland",
    abbreviation: "CH",
  },
  {
    from: "surinamesa",
    country_name: "Suriname",
    country_name_int: "Suriname",
    abbreviation: "SR",
  },
  {
    from: "svalbardense",
    country_name: "Svalbard",
    country_name_int: "Svalbard & Jan Mayen",
    abbreviation: "SJ",
  },
  {
    from: "tadjique",
    country_name: "Tadjiquistão",
    country_name_int: "Tajikistan",
    abbreviation: "TJ",
  },
  {
    from: "tailandesa",
    country_name: "Tailândia",
    country_name_int: "Thailand",
    abbreviation: "TH",
  },
  {
    from: "taiwanês",
    country_name: "Taiwan",
    country_name_int: "Taiwan",
    abbreviation: "TW",
  },
  {
    from: "tanzaniana",
    country_name: "Tanzânia",
    country_name_int: "Tanzania",
    abbreviation: "TZ",
  },
  {
    from: "do território britânico do oceano índico",
    country_name: "Território Britânico do Oceano índico",
    country_name_int: "British Indian Ocean Territory",
    abbreviation: "IO",
  },
  {
    from: "do territórios do sul da frança",
    country_name: "Territórios do Sul da França",
    country_name_int: "French Southern Territories",
    abbreviation: "TF",
  },
  {
    from: "timorense",
    country_name: "Timor-Leste",
    country_name_int: "Timor-Leste",
    abbreviation: "TL",
  },
  {
    from: "togolesa",
    country_name: "Togo",
    country_name_int: "Togo",
    abbreviation: "TG",
  },
  {
    from: "tonganesa",
    country_name: "Tonga",
    country_name_int: "Tonga",
    abbreviation: "TO",
  },
  {
    from: "trinitário-tobagense",
    country_name: "Trinidad e Tobago",
    country_name_int: "Trinidad & Tobago",
    abbreviation: "TT",
  },
  {
    from: "tristanita",
    country_name: "Tristão da Cunha",
    country_name_int: "Tristan da Cunha",
    abbreviation: "TA",
  },
  {
    from: "tunisiana",
    country_name: "Tunísia",
    country_name_int: "Tunisia",
    abbreviation: "TN",
  },
  {
    from: "turcomana",
    country_name: "Turcomenistão",
    country_name_int: "Turkmenistan",
    abbreviation: "TM",
  },
  {
    from: "turca",
    country_name: "Turquia",
    country_name_int: "Turkey",
    abbreviation: "TR",
  },
  {
    from: "tuvaluana",
    country_name: "Tuvalu",
    country_name_int: "Tuvalu",
    abbreviation: "TV",
  },
  {
    from: "ucraniana",
    country_name: "Ucrânia",
    country_name_int: "Ukraine",
    abbreviation: "UA",
  },
  {
    from: "ugandense",
    country_name: "Uganda",
    country_name_int: "Uganda",
    abbreviation: "UG",
  },
  {
    from: "uruguaia",
    country_name: "Uruguai",
    country_name_int: "Uruguay",
    abbreviation: "UY",
  },
  {
    from: "uzbeque",
    country_name: "Uzbequistão",
    country_name_int: "Uzbekistan",
    abbreviation: "UZ",
  },
  {
    from: "vanuatuense",
    country_name: "Vanuatu",
    country_name_int: "Vanuatu",
    abbreviation: "VU",
  },
  {
    from: "vaticano",
    country_name: "Vaticano",
    country_name_int: "Vatican City",
    abbreviation: "VA",
  },
  {
    from: "venezuelana",
    country_name: "Venezuela",
    country_name_int: "Venezuela",
    abbreviation: "VE",
  },
  {
    from: "vietnamita",
    country_name: "Vietnã",
    country_name_int: "Vietnam",
    abbreviation: "VN",
  },
  {
    from: "wallis-futunense",
    country_name: "Wallis e Futuna",
    country_name_int: "Wallis & Futuna",
    abbreviation: "WF",
  },
  {
    from: "zambiana",
    country_name: "Zâmbia",
    country_name_int: "Zambia",
    abbreviation: "ZM",
  },
  {
    from: "zimbabuana",
    country_name: "Zimbábue",
    country_name_int: "Zimbabwe",
    abbreviation: "ZW",
  },
];
