version: "3"

services:
  app:
    build: .
    command: yarn dev
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=database
    volumes:
      - ".:/usr/app"

  database:
    image: mongo
